services:
  fastapi:
    container_name: fastapi
    build: ./fastapi
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app/
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: local
